### PR TITLE
manifest: update fw-nrfconnect-zephyr

### PR DESCRIPTION
**Pull request by rlubos**
Introduce recent upmerge.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
```
In file included from /jenkins_workspace/workspace/fw-nrfconnect-nrf_PR-814/zephyr/soc/arm/nordic_nrf/nrf91/linker.ld:9:0:
/jenkins_workspace/workspace/fw-nrfconnect-nrf_PR-814/zephyr/include/arch/arm/cortex_m/scripts/linker.ld:258:10: fatal error: snippets-rodata.ld: No such file or directory
 #include <snippets-rodata.ld>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by rlubos** [comment]
@pdunaj yes, I am aware of it. For whatever reason this file is not created for the spm, I'm trying to figure out why.

**Comment by pdunaj** [comment]
Is it generating for anything else other then `zephyr_linker_sources(SECTIONS)`?

**Comment by pdunaj** [comment]
it's green :) let's merge it :)

**Comment by rlubos** [comment]
`fw-nrfconnect-zephy` is now merged, updated the commit SHA here.

**Pull request merged**
