### PR TITLE
Sensor and GPS simulator stack fix

### PR DESCRIPTION
**Pull request by jtguggedal**
The sensor and GPS simulators run threads which have stacks as members of a driver data struct. Generally, having stacks as members of structs is discouraged in Zephyr (though common practice in drivers). After recent, unidentified changes upstream the asset tracker and other apps using these simulators would hardfault because of accessing .

These two patches removes the stacks from the structs and set them as global statics.

### CODE REVIEW

**Comment by jtguggedal** [comment]
Any insight into why this has suddenly started to fail after latest upmerge is welcome (https://github.com/NordicPlayground/fw-nrfconnect-nrf/commit/c2ec61ff9dbd72c88632faf5288d2bdc262032d2)

**Comment by lemrey** [comment]
Is it an issue that can be solved by increasing the stack size, or is it an issue with `K_THREAD_STACK_MEMBER` ?
I am asking because I use `K_THREAD_STACK_MEMBER` in code that I am developing and removing that would limit the functionality.

**Comment by jtguggedal** [comment]
I'm not sure why it started failing, and why this would fix it and if it's actually a proper fix.

**Comment by lemrey** [comment]
Then perhaps there was a regression upstream, @ioannisg could you please take a look at why `K_THREAD_STACK_MEMBER` stopped working here? I suppose that if the issue was with an overflow, then a larger stack size should have at least hidden the problem.

**Comment by ioannisg** [comment]
> 
> 
> Then perhaps there was a regression upstream, @ioannisg could you please take a look at why `K_THREAD_STACK_MEMBER` stopped working here? I suppose that if the issue was with an overflow, then a larger stack size should have at least hidden the problem.

@jtguggedal can you post some logging of the error you are getting?

**Comment by jtguggedal** [comment]
@ioannisg This is what I see when trying to run asset tracker on current master:
```
16 0x20000 0x22000      Non-Secure      rwxl                                    
17 0x22000 0x24000      Non-Secure      rwxl                                    
18 0x24000 0x26000      Non-Secure      rwxl                                    
19 0x26000 0x28000      Non-Secure      rwxl                                    
20 0x2Exception occurred in Secure State                                        
***** HARD FAULT *****                                                          
  Fault escalation (see below)                                                  
***** BUS FAULT *****                                                           
  Precise data bus error                                                        
  BFAR Address: 0x50008120                                                      
***** Hardware exception *****                                                  
Current thread ID = 0x20020470                                                  
Faulting instruction address = 0x12290                                          
Fatal fault in ISR! Spinning...   
```

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg This is what I see when trying to run asset tracker on current master:
> 
> ```
> 16 0x20000 0x22000      Non-Secure      rwxl                                    
> 17 0x22000 0x24000      Non-Secure      rwxl                                    
> 18 0x24000 0x26000      Non-Secure      rwxl                                    
> 19 0x26000 0x28000      Non-Secure      rwxl                                    
> 20 0x2Exception occurred in Secure State                                        
> ***** HARD FAULT *****                                                          
>   Fault escalation (see below)                                                  
> ***** BUS FAULT *****                                                           
>   Precise data bus error                                                        
>   BFAR Address: 0x50008120                                                      
> ***** Hardware exception *****                                                  
> Current thread ID = 0x20020470                                                  
> Faulting instruction address = 0x12290                                          
> Fatal fault in ISR! Spinning...   
> ```

Looks like you have got a SecureFault.
It might be due to stack corruption.

 Build your (Non-Secure) application with CONFIG_HW_STACK_PROTECTION=y. If this is a stack corruption, you should be getting Stack Failure, instead.

**Comment by jtguggedal** [comment]
Labelling DNM, as there is still hardfault when compiling with `CONFIG_NO_OPTIMIZATIONS` set. Need to understand the root cause better.

**Comment by jtguggedal** [comment]
Closing this PR, as it's superseded by #793 that handles the root cause of `CONFIG_FP_SHARING` not being enabled even though multiple threads use float registers.

**Comment by ioannisg** [comment]
> 
> 
> Closing this PR, as it's superseded by #793 that handles the root cause of `CONFIG_FP_SHARING` not being enabled even though multiple threads use float registers.

Just pointing out that the cause of the secure fault has not been identified; even if the root cause is the FP_SHARING being missing. 

If the problem is the Floating-Point register usage, I tend to think that the FPU interrupt might be triggered (but the ISR handler is not implemented).

**Comment by jtguggedal** [comment]
> > Closing this PR, as it's superseded by #793 that handles the root cause of `CONFIG_FP_SHARING` not being enabled even though multiple threads use float registers.
> 
> Just pointing out that the cause of the secure fault has not been identified; even if the root cause is the FP_SHARING being missing.
> 
> If the problem is the Floating-Point register usage, I tend to think that the FPU interrupt might be triggered (but the ISR handler is not implemented).

You're right. Added an ISR handler for FPU, and the interrupt is indeed triggered. Now the program proceeds some more and crashes when attempting to reschedule from idle thread:
```
***** HARD FAULT *****
Fault escalation (see below)
***** BUS FAULT *****
Precise data bus error
BFAR Address: 0x50008120
***** Hardware exception *****
Current thread ID = 0x20021bf0
Faulting instruction address = 0x2bc6a
Fatal fault in ISR! Spinning...
```

**Pull request closed without merging**
