### PR TITLE
drivers: at_cmd: Increase default AT_CMD_RESPONSE_MAX_LEN

### PR DESCRIPTION
**Pull request by jhn-nordic**
Increased the default AT_CMD_RESPONSE_MAX_LEN to support
writing of certificates used by nRF Cloud.

Signed-off-by: Jon Helge Nistad <jon.helge.nistad@nordicsemi.no>

### CODE REVIEW

**Comment by lemrey** [comment]
This was merged too quickly, there was no time to review this..
The `at_cmd` driver needs as much heap as `AT_CMD_RESPONSE_MAX_LEN`, so this has changed the heap requirements of all projects using this code, but no project configuration was updated in this PR.
Which projects requires `2700` byte long AT responses?
There was a PR not so long ago bumping this to the previous value

**Comment by bjda** [comment]
@lemrey The just-in-time client certificates used in nRF Cloud are this big (as they are 2 concatenated certs). This allows certificate updates on Thingy:91 running the asset tracker or at_host example.

**Comment by lemrey** [comment]
Thanks @bjda, does the AT command used to provision the certificates return a response that is as large as the certificates?

**Comment by bjda** [comment]
No. However, it looks like the AT host library uses this config for sizing buffers in both directions. I would propose reworking at_host to have a separate kconfig for the command buffer.

**Pull request merged**
