### PR TITLE
Bluetooth: gatt_dm: Fix assert in bt_gatt_discover

### PR DESCRIPTION
**Pull request by joerchan**
Fix assert in bt_gatt_discover API on start_handle and end_handle.
The GATT Discovery manager would provide the invalid attribute handle 0
for the start handle at the end of the discovering all services.
At this point the end_handle is 0xffff, so when start handle is set to
end handle + 1 it would cause an integer overflow to 0.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Comment by rakons** [comment]
It looks like a hack. I am wondering why discover func with attr set to NULL is not called. Maybe it has something in common with that statement from the documentation:

> If discovery procedure has completed this callback will be called with
> *  attr set to NULL. **This will not happen if procedure was stopped by returning BT_GATT_ITER_STOP.** The attribute is read-only and cannot be cached without copying its contents.

**Comment by joerchan** [comment]
> It looks like a hack. I am wondering why discover func with attr set to NULL is not called. Maybe it has something in common with that statement from the documentation:
> 
> > If discovery procedure has completed this callback will be called with
> > 
> > * attr set to NULL. **This will not happen if procedure was stopped by returning BT_GATT_ITER_STOP.** The attribute is read-only and cannot be cached without copying its contents.
> 
> I will look into it.

@rakons It is because we never BT_GATT_CONTINUE from the gatt_dm discovery callback.
Instead we start a new bt_gatt_discover manually, so we need to do this handling ourselves.
Have a look here:

```
	params->start_handle = last_handle;
	if (params->start_handle < UINT16_MAX) {
		params->start_handle++;
	} else {
		goto done;
	}
...

done:
	params->func(conn, NULL, params);
```
(Sorry I messed up earlier and ended up editing your comment)

**Comment by grochu** [comment]
@joerchan, @rakons  This should have the `backport v1.1-branch` label, to make sure it gets to NCS 1.1.0. But before it is back-ported, https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1432 needs to be back-ported too.

**Comment by joerchan** [comment]
@grochu Unless we have a very good reason we will no backport Bluetooth related bugs to the v1.1. Do you have reason for needing this in v1.1 (as well as 1432)?

@rakons Will include a short sample before merging this.

**Comment by grochu** [comment]
> @grochu Unless we have a very good reason we will no backport Bluetooth related bugs to the v1.1. Do you have reason for needing this in v1.1 (as well as 1432)?

Not really, I thought the Verification wanted in the release all BLE bugs detected during release testing. If this one doesn't fix an issue from release testing, then we can merge just to master.

**Comment by joerchan** [comment]
> Not really, I thought the Verification wanted in the release all BLE bugs detected during release testing. If this one doesn't fix an issue from release testing, then we can merge just to master.

Ok. This one was reported by a user.

Will take sample in a new PR.

**Pull request merged**
