### PR TITLE
Bluetooth: Samples: Switch to synchronous bt_init before main loop

### PR DESCRIPTION
**Pull request by joerchan**
Switch to using the synchronous bt_init call before starting the main
loop in the peripheral samples. This is to avoid sending notifications
before bluetooth has been properly initialized.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
Is there a reason for not applying this change for uses of `bt_enable()`?

**Comment by kapi-no** [comment]
@joerchan, what about throughput sample. It has the same structure as LLPM sample.

Generally, I think we should use one type of initialization in all BLE samples (synchronous API in this case) to have a more standardized sample structure. It would be easier for users to switch between samples / understand new ones if they all share a common structure.

**Comment by joerchan** [comment]
> @joerchan, what about throughput sample. It has the same structure as LLPM sample.
> 
> Generally, I think we should use one type of initialization in all BLE samples (synchronous API in this case) to have a more standardized sample structure. It would be easier for users to switch between samples / understand new ones if they all share a common structure.

@kapi-no The difference between LLPM sample and throughput sample is the call to `enable_qos_conn_evt_report` which will call `bt_hci_cmd_send`. This API call needs to wait for the bt_ready to have been processed. Otherwise all other calls are fine. The main loop is waiting for `test_ready` flag to have been set, or calling `bt_conn_cb_register` which don't have to wait for bt_ready to have been processed.

Some samples have a semaphore that they wait for before starting the main loop, others do everything in the callbacks and just return from main (or blink led in main).
I'm fine with aligning the samples to a common template. But I'd prefer to do that outside of this PR.

**Comment by joerchan** [comment]
> Is there a reason for not applying this change for uses of `bt_enable()`?

Could you clarify this question?

**Comment by rugeGerritsen** [comment]
> Is there a reason for not applying this change for uses of bt_enable()?
> 
> @rugeGerritsen Could you clarify this question?

I would assume it is more future proof if all examples use the same approach. Then we don't rely on ordering of calls to the controller/host

**Comment by joerchan** [comment]
@kapi-no @rugeGerritsen Should we switch to using a semaphore before continuing the main thread then? The peripheral_lbs sample and some other use this approach.

**Comment by rugeGerritsen** [comment]
> @kapi-no @rugeGerritsen Should we switch to using a semaphore before continuing the main thread then? The peripheral_lbs sample and some other use this approach.

I'm fine with either. To me, it seems like using synchronous initialization is the simplest solution

**Comment by carlescufi** [comment]
> Make all samples use the same initialization method

@joerchan can you please check all samples?

**Comment by joerchan** [comment]
> > Make all samples use the same initialization method
> 
> @joerchan can you please check all samples?

@carlescufi @rugeGerritsen But which method? Synchronous or semaphore, I'm not sure a black "all the same" makes sense as this is only needed in the case where the sample is doing BT calls in the main loop.
In that case there are 2 options, a semaphore and async, or sync.
In the cases where everything is done in the callback having sync or a semaphore makes no sense.
@kapi-no Do you have any opinions on this?

**Comment by joerchan** [comment]
> > > Make all samples use the same initialization method
> > 
> > 
> > @joerchan can you please check all samples?
> 
> @carlescufi @rugeGerritsen But which method? Synchronous or semaphore, I'm not sure a black "all the same" makes sense as this is only needed in the case where the sample is doing BT calls in the main loop.
> In that case there are 2 options, a semaphore and async, or sync.
> In the cases where everything is done in the callback having sync or a semaphore makes no sense.
> @kapi-no Do you have any opinions on this?

**Comment by lemrey** [comment]
In most cases we can have it synchronous, and decide whether we prefer to do the setup in main or in a separate `bt_ready` function for clarity. Where it does not need to be synchronous, we could pass `bt_ready` to `bt_enable`. A couple of samples would need more changes as one does not have `main` thread and another sleeps after `bt_enable`.. I could do this if you'd like @joerchan.

**Comment by joerchan** [comment]
> In most cases we can have it synchronous, and decide whether we prefer to do the setup in main or in a separate `bt_ready` function for clarity. Where it does not need to be synchronous, we could pass `bt_ready` to `bt_enable`. A couple of samples would need more changes as one does not have `main` thread and another sleeps after `bt_enable`.. I could do this if you'd like @joerchan.

@lemrey Happy to. I have included the changes I already made to peripheral_lbs sample. I think UART and NUS might need something similar.

**Comment by kapi-no** [comment]
> 
> 
> > > Make all samples use the same initialization method
> > 
> > 
> > @joerchan can you please check all samples?
> 
> @carlescufi @rugeGerritsen But which method? Synchronous or semaphore, I'm not sure a blank "all the same" makes sense as this is only needed in the case where the sample is doing BT calls in the main loop.
> In that case there are 2 options, a semaphore and async, or sync.
> In the cases where everything is done in the callback having sync or a semaphore makes no sense.
> @kapi-no Do you have any opinions on this?

I would use the simplest solution - sync one - like it is now done in this PR and also cover remaining samples so all BLE samples are aligned on this.

**Comment by lemrey** [comment]
I have updated the samples to call `bt_enable` synchronously.
I removed the `bt_ready` function since half of the samples used it, half didn't, and those that did have it did different things in it, so I put all the initialization code in main instead.

**Pull request merged**
