### PR TITLE
manifest: update manifest to include nrf_security v1.0.0 fixes

### PR DESCRIPTION
**Pull request by tejlmand**
Update nrfxlib revision to pull/64/head
with various fixes for nrf_security Kconfig and CMake updates.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

### CODE REVIEW

**Comment by thst-nordic** [comment]
Doc build has some errors still. 

https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/test-fw-nrfconnect-nrf_documentation/detail/master/2978/pipeline/

**Comment by thst-nordic** [comment]
Once PR-64 is merged, this needs to be converted to a SHA right?

**Comment by frkv** [comment]
> Once PR-64 is merged, this needs to be converted to a SHA right?

Correct.

**Comment by lemrey** [comment]
What's the status on this?

**Comment by thst-nordic** [comment]
@tejlmand, can you rebase the v1.0-branch?   There are required changes in the CI pipeline that you are missing.

**Comment by tejlmand** [comment]
Obdolete

**Pull request closed without merging**
