### PR TITLE
subsys: esb: remove nrf prefix

### PR DESCRIPTION
**Pull request by lemrey**
There were a number of tasks to be done for ESB.
For now I just removed the prefix but I might add more commits.

I'd think the tests need to be updated, right @magnev ?
What about documentation, @ru-fu ?

### CODE REVIEW

**Comment by ru-fu** [comment]
For documentation:
- The rst file must be renamed as well.
- All references to objects & doxygen objects in the (nrf_)esb.rst file, the user guide (doc/nrf/ug_esb.rst), and maybe the sample readme file must be updated.
- Need to check if the doc build is green (also need to upmerge, there were problems on master).

Will you do that? Do you want me to do it?

**Comment by lemrey** [comment]
@ru-fu I can fix that, thank you.

**Comment by magnev** [comment]
@lemrey Yes, the test application needs to be updated. I will take a look at it.

**Comment by thst-nordic** [comment]
Can I cancel this PR?

**Comment by lemrey** [comment]
@magnev do you think we can merge this?

**Comment by lemrey** [comment]
Changelog updated.

**Pull request merged**
