### PR TITLE
Upmerge December

### PR DESCRIPTION
**Pull request by SebastianBoe**
bump hal_nordic and ci-tools

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
I was so fare unable to run BLE DFU using smp_svr examle on nrf52840_pca10056 - have to recheck my HW setup - @hakonfam or @SebastianBoe were you able to make FWU.

**Comment by SebastianBoe** [comment]
> I was so fare unable to run BLE DFU using smp_svr examle on nrf52840_pca10056 - have to recheck my HW setup - @hakonfam or @SebastianBoe were you able to make FWU.

This issue is believed to be resolved.

**Comment by SebastianBoe** [comment]
DNM until manifest is SHA'ified

**Comment by pdunaj** [comment]
@SebastianBoe would it be possible to include https://github.com/zephyrproject-rtos/zephyr/pull/21420 in the upmerge? Or will it have to wait for the next train?

**Comment by SebastianBoe** [comment]
> @SebastianBoe would it be possible to include zephyrproject-rtos/zephyr#21420 in the upmerge?

@pdunaj : Done.

**Pull request merged**
