### PR TITLE
lib: bsdlib: Add socket offloading for sockopt options

### PR DESCRIPTION
**Pull request by stig-bjorlykke**
Added sockopt support for socket level SOL_SOCKET with new options:
SO_ERROR, SO_RCVTIMEO and SO_BINDTODEVICE.

Use translated level and optname to nrf_getsockopt() and translate
the returned optval from nRF error to native error.

Signed-off-by: Stig Bjørlykke <stig.bjorlykke@nordicsemi.no>

### CODE REVIEW

**Comment by stig-bjorlykke** [comment]
This PR requires fw-nrfconnect-zephyr PR #97.

**Comment by rlubos** [comment]
Manifest got updated, please rebase.

**Comment by stig-bjorlykke** [comment]
Now the only missing dependency should be PR#30 from nrfxlib.

**Comment by rlubos** [comment]
Ehh, I wasn't aware that there are more dependencies for this, will have to update manifest again. Any chance we do it in this PR, just to speed up the process? Just please add a commit in a same manner as https://github.com/NordicPlayground/fw-nrfconnect-nrf/commit/970584cd6f8a9793f67e8114dbfea84801cc1226.

Preferably, add it before https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/448/commits/dd723380ea4013bc8fa360684ba12fe1b53db11e, so that both commits build.

**Comment by rlubos** [comment]
Thank you

**Comment by stig-bjorlykke** [comment]
I tried to split the work into separate commits for easier review, but this resulted in multiple dependencies between repos. I'll try to avoid this next time.

**Pull request merged**
