### PR TITLE
bluetooth: controller: Update west to ble_controller_0.3.0-3.prealpha

### PR DESCRIPTION
**Pull request by rugeGerritsen**
This controller adds support for nRF52833 and fixes hci_data_get()
when multiple devices are connected.

Signed-off-by: Rubin Gerritsen <Rubin.Gerritsen@nordicsemi.no>

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
FYI: @joerchan, @pdunaj

**Comment by joerchan** [comment]
CC: @kapi-no, @grochu, @rakons or @KAGA164
This is a bugfix release for the BLE controller, could you check if this has any effects on the BLE samples?

@pdunaj or @MarekPieta Can you verify that this fixes the issue you have?

**Comment by MarekPieta** [comment]
Hi,
I briefly checked that the changes works nicely for us and fix some of the found issues.
I will make more detailed tests and I will inform you if I find any problems.

**Comment by kapi-no** [comment]
@joerchan, thanks for keeping us in the loop!

We will let you know in case we find any issues

**Comment by kapi-no** [comment]
CC: @rafpelc, @qung, @elisabeth-solheim

**Pull request merged**
