### PR TITLE
samples: openthread: Disable error after power up and debug optimization

### PR DESCRIPTION
**Pull request by MarekPorwisz**
Error showing after power up of application has been disabled as it is
expected at the moment. Debug optimizations has been disabled and the
folder has been renamed to remove redundant openthread indications.

Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>

### CODE REVIEW

**Comment by greg-fer** [comment]
Two things:

1) What exactly was wrong with the previous name of the sample? Was having `ot_` there the only issue? If so, I think it was actually useful to distinguish this sample from CLI samples for Zigbee or other technologies that would come in the future.

2) If I remember correctly, we discussed the idea that the name of the sample would also match the tag of the rst page. Now they are different (`common_line_interface` vs `ot_cli_sample`). This might lead to some discrepancies that are also present in nRF5 SDK for Thread and make identifying examples there particularly cumbersome. Can you modify the tag, so that it matches the title of the sample and the name of the directory?

**Comment by MarekPorwisz** [comment]
> Two things:
> 
> 1. What exactly was wrong with the previous name of the sample? Was having `ot_` there the only issue? If so, I think it was actually useful to distinguish this sample from CLI samples for Zigbee or other technologies that would come in the future.
Both @lmaciejonczyk and @rlubos reported this as an issue. The sample is already in an openthread subfolder so there is no need for an additional subfolder prefix.

> 2. If I remember correctly, we discussed the idea that the name of the sample would also match the tag of the rst page. Now they are different (`common_line_interface` vs `ot_cli_sample`). This might lead to some discrepancies that are also present in nRF5 SDK for Thread and make identifying examples there particularly cumbersome. Can you modify the tag, so that it matches the title of the sample and the name of the directory?
My understanding of an anchor was exactly the opposite of what you wrote. Anchors are used so that the directory and name can be easily changed without the need of modifying all the places that link to it. Why not link to a file instead then? I'll update it. Will  _openthread_command_line_interface anchor name be ok?

**Comment by rlubos** [comment]
If it was me, I'd just call it `cli`, that's how the sample is called in OpenThread and in the "old" SDK. I think that the fact it's in `openthread` subdirectory, clearly identifies its purpose.

**Comment by lmaciejonczyk** [comment]
Shouldn't it be not `common_line_interface`, but rather `command_line_interface` anyway.

**Comment by lmaciejonczyk** [comment]
> Anchors are used so that the directory and name can be easily changed without the need of modifying all the places that link to it. Why not link to a file instead then? 

Good point.

For me better is `command_line_interface`, it just explicitly says what the sample is. From legacy reason `cli` is good name too.

**Comment by rlubos** [comment]
I think that rebase should help with the CI.

**Pull request merged**
