### PR TITLE
manifest: Updates MPSL + BLE Controller

### PR DESCRIPTION
**Pull request by rugeGerritsen**
Fixes the return type of Zephyr Write TX Power.
Some minor size optimizations.

See https://github.com/NordicPlayground/nrfxlib/pull/147

Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
@MarekPieta . This PR includes the fix you requested.
@grochu, do you want to do manual testing on this one?

**Comment by MarekPieta** [comment]
This fixes reported issue. Thank you.

**Comment by joerchan** [comment]
@grochu Is there something lacking in the automatic testing? nrf53 throughput test?

**Comment by grochu** [comment]
> @grochu Is there something lacking in the automatic testing? nrf53 throughput test?

Hi, I don't have the time to test today, so maybe let's merge the PR. All the nRF53 tests are on a branch currently, so the CI doesn't include them. They are not merged to master because there is a failing test case - I will look at it next week.

**Pull request merged**
