### PR TITLE
samples: adafruit: lcd: add Adafruit LCD LittlevGL sample

### PR DESCRIPTION
**Pull request by leewkb4567**
Add a sample application that runs LittlevGL tutorials on an
Adafruit LCD touch shield.

Signed-off-by: Bernard Lee <bernard.lee@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
@leewkb4567 Thanks for this! It looks pretty good already. I am just wondering whether we want this here downstream or maybe upstream in Zephyr? The reason is that this doesn't seem tied to nRF hardware in particular in any way, so it might be good for the whole community to benefit from it? @jdstapes thoughts?

**Comment by leewkb4567** [comment]
@carlescufi This LCD demo code should also work on upstream Zephyr. Upstream has a LittlevGL sample which works on several boards. This demo code takes a different path. No Zephyr display driver is done. The application feeds the display and touch panel inputs to LittlevGL directly. Up to your guys’ evaluation. 😊

**Comment by rakons** [comment]
I do not understand the reason of putting the whole display driver into the application - why we cannot just put ili9341 driver next to ili9340 driver inside ./drivers/display folder? What is the idea behind implementing totally different approach that the one implemented already? Any pros?

**Comment by leewkb4567** [comment]
The scenario is that I am making a LittlevGL demo code with minimal coding. 😊 Without the display API abstraction, the program flow is more straightforward.

This demo code uses the ILI9341 in 16-bit RGB format. The upstream Zephyr display driver needs to be modified for 16-bit support.

Taking a look at the related files.
zephyr\include\display.h
zephyr\drivers\display\display_ili9340.c
zephyr\lib\gui\lvgl\lvgl.c

==> The display driver supports pixel formats of 1-bit, 24-bit & 32-bit.
==> The ili9340 and lvgl modules are actually initialized at application priority.
==> The LittlevGL initialization handles only the display driver. The application needs to register the touch panel driver to LittlevGL.

**Comment by leewkb4567** [comment]
Hmm… Zephyr has a 16-bit RGB sample driver now. It was integrated a few days ago.

A general purpose ILI9341 display driver takes more than my current demo code.
==> The Zephyr display driver buffer has a pitch parameter.
==> The Adafruit sample code uses the LCD in portrait orientation. I modified the configuration to landscape orientation because it looks nicer with our DK.
==> I have also a Seeed LCD shield which uses ILI9341 differently. The screen orientation takes different configuration values.

**Comment by lemrey** [comment]
Hi @leewkb4567, thank you very much for this patch. I would suggest to try and submit it upstream, and to split the driver and application code. That way it can be more useful for everybodyand hopefully you can receive some help from the community, so it would be easier to maintain.

**Comment by leewkb4567** [comment]
Agree. The feature is easier to maintain after organization. Thank you.

**Pull request closed without merging**
