### PR TITLE
applications: nrf_desktop: Switch to Nordic LL

### PR DESCRIPTION
**Pull request by pdunaj**
Jira:DESK-228

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
I have checked that change with mouse and dongle. Both work.
Connecting and reconnecting to dongle works fine. Connecting to Windows 7 (Intel driver) works fine. I have problem with reconnecting but this can be due to my host (for some reason it thinks that device is connected, even when I actually turn off the mouse).

**Comment by pdunaj** [comment]
Hi @wiminordic , can you test this one extensively?

**Comment by MarekPieta** [comment]
btw. in second commit you removed all keyboard configurations, not only the ones with bootloader

**Comment by pdunaj** [comment]
To clarify - the second commit was to make CI build the artifacts for Wiktor, so he can test the mouse.
I will check the memory usage and update the partitions. To be honest I don't like the fact that new LL takes more RAM and ROM.

**Pull request closed without merging**
