### PR TITLE
nrf_cc310: Added description for cc310 drivers

### PR DESCRIPTION
**Pull request by tejlmand**
Doc commit from: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1268

nrf_cc310: Added description for cc310 drivers
    
Added description for:
- cc310 entropy driver
- cc310 hw initialization
    
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

### CODE REVIEW

**Comment by b-gent** [comment]
I'm assuming this is for 1.1.0? If yes, please add the backport label @tejlmand @frkv

**Comment by b-gent** [comment]
I added another commit as a result of Frank's comments. @frkv , please check the diff. 

Also, as part of this PR, a file ``rtt_README.rst`` was moved from ``nrf/drivers/net`` to ``doc/nrf/drivers``. I reverted this change, this RST file is not reviewed and I don't want it to show up in the output.

**Comment by b-gent** [comment]
> The APIs in nrf_cc310_mbedcrypto are also usable

For this, I just provided a link to library description as we don't have API doc for this (header files do not have any doxygen groups defined)

**Comment by tejlmand** [comment]
> Also, as part of this PR, a file `rtt_README.rst` was moved from `nrf/drivers/net` to `doc/nrf/drivers`. I reverted this change, this RST file is not reviewed and I don't want it to show up in the output.

This is fine with me.
The main reason for including this file, was because the initial PR has the `entropy_cc310.rst` and `hw_cc310.rst` located in `drivers/*` and not in `doc/nrf/drivers/*` and this caused `rtt_README.rst` to show up during doc build with a warning it was not included in the docs.

When rst files has been moved to `doc/nrf/drivers`, this is no longer an issue.

**Comment by b-gent** [comment]
looking good, thanks

**Comment by tejlmand** [comment]
@b-gent squashed commits.

**Comment by carlescufi** [comment]
@b-gent will you merge this?

**Comment by b-gent** [comment]
merged

**Pull request merged**
