### PR TITLE
net: lib: download_client: move header and minor updates

### PR DESCRIPTION
**Pull request by lemrey**
- Move header under `/net`.
- Rename C file to match header file.
- Make a couple of API parameters `const`.
- Update a couple of log strings.
- Align KConfig macro names.

### CODE REVIEW

**Comment by lemrey** [comment]
@rlubos I have added one commit to align Kconfig macro names and remove the NRF prefix.

**Comment by rlubos** [comment]
@lemrey Ack, looks good, approve still valid :)

**Comment by lemrey** [comment]
Reminder to self: update changelog.

**Comment by lemrey** [comment]
Changelog updated.

**Pull request merged**
