### PR TITLE
samples: nrf_desktop: Turn off charger and LED driver

### PR DESCRIPTION
**Pull request by pdunaj**
Jira:DESK-297

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
tested on PCA20041

**Comment by wiminordic** [comment]
nrf_desktop_test failing due to DESK-502. This issue is already in master. No other problems.

**Comment by pdunaj** [comment]
I have left the NFC pins set to zero as otherwise current leaked there (I am not really sure why to be honest will check with Martin).

**Comment by pdunaj** [comment]
Hi @pizi-nordic , could you merge?

**Pull request merged**
