### PR TITLE
doc: partition_manager: use "the" consistently

### PR DESCRIPTION
**Pull request by mbolivar**
Add "the" before uses of Partition Manager which do not have an
article already.

### CODE REVIEW

**Comment by mbolivar** [comment]
@ru-fu happy new year! This is related to discussion in https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1605, where you expressed a preference for "the" before "Partition Manager" in this documentation.

If this is agreeable to you and we can merge it, I will rebase #1605 on top and keep things consistent there.

**Comment by mbolivar** [comment]
@ru-fu ping?

**Comment by hakonfam** [comment]
@b-gent trying my luck, these are tiny changes :)

**Comment by ru-fu** [comment]
This PR is on my list and I will look at it. It's not the most urgent though. ;)

**Comment by mbolivar** [comment]
> I added a few more "the"s to really be consistent. ;)
> 
> Please squash if you're happy with it.

Squashed, thanks!

**Pull request merged**
