### PR TITLE
Ble controller: Support configurable dle

### PR DESCRIPTION
**Pull request by rugeGerritsen**
Also fixed an issue on nRF53 where the radio stayed in the TX state longer than expected.

### CODE REVIEW

**Comment by joerchan** [comment]
@rugeGerritsen I rebased and force-pushed

**Comment by bukinr** [comment]
I can't set NRF_LF_CLOCK_SRC_XTAL after this comment with an assertion here:
ble_assertion_handler: ../stack/projects/ble_controller/src/ble_controller.c:126

**Comment by joerchan** [comment]
@rugeGerritsen Can you have a look at this. Seems like that assert should return the error code instead since it is affected by application input.

@bukinr Your XTAL config is probably incorrect. Make sure that rc_ctiv and rc_temp_ctiv are both set to zero. The reason for RC not working is probably the accuracy configuration. Should be set to 500 for RC I think.

**Comment by bukinr** [comment]
@joerchan Thanks setting rc_ctiv and rc_temp_ctiv to zero resolves my issue.
However it does not pair some times with XTAL (about 50% chance). Before this commit it was 100% working with XTAL.

With RC I never get paired even I set accuracy to 500PPM (both this and previous version): the acl with a paring request never received by nrf5340 after establishing connection.

PS. I'm only trying to pair with Xiaomi MI9 Lite (bt 5.0).

**Comment by bukinr** [comment]
Oh, sorry I think it is working fine with XTAL. Probably my issue (50% pairing) was caused by excessive debugging in the HCI stack (application MCU).

My code is here: https://github.com/machdep/nrf5340

**Pull request merged**
