### PR TITLE
samples: nfc: add support for nRF5340

### PR DESCRIPTION
**Pull request by kapi-no**

### CODE REVIEW

**Comment by kapi-no** [comment]
CC: @rafpelc

**Comment by grochu** [comment]
1 general comment: since these samples run only on APP core, does the code in _nrf5340_cpunet_reset.c_ have any effect? If the flash on NET is cleared, nothing will happen, but if it is not, maybe the NET should not be "released"? But this is rather a topic for a separate issue/PR.

**Comment by kapi-no** [comment]
@grochu, yes, it is better not to start Network Core so that it draws as little current as possible in the case that you described.

**Comment by kapi-no** [comment]
@joerchan, could you please merge it?

**Pull request merged**
