### PR TITLE
samples: nrf_desktop: New version of PCA20041

### PR DESCRIPTION
**Pull request by pdunaj**
Adjust pin usage for buttons, optical sensor and LED driver.
Fix row reading in buttons module.
Use level interrupts in buttons module.

Signed-off-by: Filip Kubicz <filip.kubicz@nordicsemi.no>
Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by wiminordic** [comment]
Replaced the HW in on-commit server. Try force pushing to trigger new build.

**Comment by pdunaj** [comment]
it seems there were some left overs; last push should fix it

**Comment by pdunaj** [comment]
Hi @wiminordic , can we switch now?

**Comment by wiminordic** [comment]
> Hi @wiminordic , can we switch now?

Yes, from test perspective everything is ok.

**Comment by pdunaj** [comment]
Hi @jhn-nordic , @MarekPieta , @Qbicz , @wiminordic , once merged project switches to new HW version.

**Pull request merged**
