### PR TITLE
ci: add nrf53 ble samples to sanitycheck

### PR DESCRIPTION
**Pull request by thst-nordic**
- add 'nrf5340_dk_nrf5340_cpuapp' to bluetooth samples

Signed-off-by: Thomas Stilwell <Thomas.Stilwell@nordicsemi.no>

### CODE REVIEW

**Comment by kapi-no** [comment]
Please remove nRF53 target for the Throughput sample for now. ```sys_rand32_get``` is undefined for the Application Core, because it has no RNG peripheral. It is not possible to use throughput sample on nRF53 (since changes introduced by #1759).

**Comment by kapi-no** [comment]
A build error for the throughput sample is fixed in #1784. The PR is expected to be merged by the end of the day

**Comment by thst-nordic** [comment]
waiting for #1784

**Comment by joerchan** [comment]
> waiting for #1784

Merged it

**Comment by kapi-no** [comment]
@thst-nordic, please rebase, CI should be green now

**Comment by thst-nordic** [comment]
rebased & CI started.

**Pull request merged**
