### PR TITLE
Hids naming alignment

### PR DESCRIPTION
**Pull request by kapi-no**
Aligning according to naming conventions

### CODE REVIEW

**Comment by lemrey** [comment]
Thanks for doing this, I tried to find some time to do it but was busy. I had a look the other day and found that some API would become very long if we simply added the `bt_gatt_`, for example
- `bt_gatt_hids_boot_mouse_inp_rep_send()`
- `bt_gatt_hids_boot_kb_inp_rep_send()`

**Comment by kapi-no** [comment]
Yes, we can shorten it - my suggestion:
`bt_gatt_hids_boot_mouse_inp_rep_send()` -> 'bt_gatt_hids_bm_inp_rep_send()'
`bt_gatt_hids_boot_kb_inp_rep_send()` -> `bt_gatt_hids_bk_inp_rep_send()`
I'm open to other suggestions

**Comment by ru-fu** [comment]
Same result, so something is breaking the documentation here.

**Comment by lemrey** [comment]
> Yes, we can shorten it - my suggestion:
> `bt_gatt_hids_boot_mouse_inp_rep_send()` -> `bt_gatt_hids_bm_inp_rep_send()`
> `bt_gatt_hids_boot_kb_inp_rep_send()` -> `bt_gatt_hids_bk_inp_rep_send()`
> I'm open to other suggestions

I suppose that's shorter, though `bm` and `bk` are a bit cryptic. What about shortening the input and output reports? `inp_rep` and `outp_rep` could be shortened to `irep` and `orep`, this could be applied to a lot of data types too, which is nice.

I am not too familiar with HID but are there mouse and keyboard reports which are not boot reports and conversely are there boot reports which are not keyboard or mouse?

**Comment by kapi-no** [comment]
> `inp_rep` and `outp_rep` could be shortened to `irep` and `orep`, this could be applied to a lot of data types too, which is nice.

That's fine too, but the gain for boot API functions is only 3 characters in this case. I don't think that's a big difference. Should we combine them?

> I am not too familiar with HID but are there mouse and keyboard reports which are not boot reports and conversely are there boot reports which are not keyboard or mouse?

No and no, boot reports are either mouse or keyboard reports and they can be used when the HID device is in the boot mode. In the protocol mode, regular (more generic) reports are used to transmit data for keyboard/mouse any other device.

**Comment by lemrey** [comment]
Yes, we should try and squeeze somewhere else.

> No and no, boot reports are either mouse or keyboard

Perhaps the `boot_` prefix could be dropped, since `mouse` and `keyboard` reports are implicitely `boot` reports?

**Comment by kapi-no** [comment]
> Perhaps the `boot_` prefix could be dropped, since `mouse` and `keyboard` reports are implicitely `boot` reports?

I think that this prefix should stay because it signals to the user when this API can be used (only in the boot mode).

@rakons, @grochu, What's your take on it? Any ideas on how to make HIDS API names shorter?

**Comment by ru-fu** [comment]
I added a commit that fixes the doc build failure. Please squash.

**Comment by carlescufi** [comment]
@kapi-no can you include @ru-fu 's commit in one of yours?

**Comment by kapi-no** [comment]
I will do it when this PR is ready. However, we need to decide first how to shorten names of 2 API functions that became too long (discussion with @lemrey)

**Comment by grochu** [comment]
> Yes, we can shorten it - my suggestion:
> `bt_gatt_hids_boot_mouse_inp_rep_send()` -> `bt_gatt_hids_bm_inp_rep_send()`
> `bt_gatt_hids_boot_kb_inp_rep_send()` -> `bt_gatt_hids_bk_inp_rep_send()`
> I'm open to other suggestions

Hi, I like this approach. We should keep consistency with the prefixes, while "_boot_mouse_"/"_boot_kb_" part can be shortened.

**Comment by rakons** [comment]
> 
> 
> > Yes, we can shorten it - my suggestion:
> > `bt_gatt_hids_boot_mouse_inp_rep_send()` -> `bt_gatt_hids_bm_inp_rep_send()`
> > `bt_gatt_hids_boot_kb_inp_rep_send()` -> `bt_gatt_hids_bk_inp_rep_send()`
> > I'm open to other suggestions
> 
> Hi, I like this approach. We should keep consistency with the prefixes, while "_boot_mouse_"/"_boot_kb_" part can be shortened.

I do not like it. As it makes it more cryptic in a sake of gaining 5 letters. We should assume some standard and keep it.

**Comment by kapi-no** [comment]
@carlescufi, I squashed the commits. Please merge

(boot functions API renames or any other renames should be done in the separate PR - this is just alignment with naming conventions, "bt_gatt_" prefix was added)

**Pull request merged**
