### PR TITLE
lib: nrf_cloud: Switch to Zephyr MQTT

### PR DESCRIPTION
**Pull request by rlubos**
This PR switches nrf_cloud library to the Zephyr upstream MQTT implementation. As the API changed sligtly, the code is aligned as well. The internal copy of MQTT is removed.

The PR is based on #263, so it has to be merged first, then I'll rebase.

### CODE REVIEW

**Comment by lemrey** [comment]
The issue here is that `bsdlib` is setting a misleading `errno` (`-ENOTSUP`) when it runs out of memory, causing this MQTT implementation to fail and trigger a disconnection.
CC: @gbakke @oxalistriangularis

**Comment by jtguggedal** [comment]
Would this PR fix the issue causing compilation to fail for the asset tracker when logs are enabled?
Compilation fails due to undeclared `CONFIG_MQTT_LOG_LEVEL`, which seemingly is depending on the upstream MQTT.

**Comment by rlubos** [comment]
@jtguggedal Seems that incorrect module name was used in the recent fix for the internal MQTT copy, it should use `CONFIG_MQTT_SOCKET_LOG_LEVEL` instead of `CONFIG_MQTT_LOG_LEVEL`. Beside of that I'm pretty sure we'd need an upmerge on the `nrf91` branch to get the recent fixes for `NET_RAW_MODE` logging.

And finally yes, having this merged would relieve us from the maintanance effort on the local copy of the library, and prevent from situations from previous upmerge, where the library was broken due to upstream changes.

**Comment by rlubos** [comment]
@joakimtoe Waiting for a bugfix in `bsdlib` for the issue described by @lemrey 

> The issue here is that bsdlib is setting a misleading errno (-ENOTSUP) when it runs out of memory, causing this MQTT implementation to fail and trigger a disconnection.

**Comment by lemrey** [comment]
> What is blocking this? It would be very nice to get this change in.

I agree, however the necessary fix might not come until March :/

**Comment by joakimtoe** [comment]
@rlubos @lemrey Ok, thank you for explaining!

**Comment by rlubos** [comment]
Closing, will reopen from a new fork.

**Pull request closed without merging**
