### PR TITLE
samples: nrf_desktop: Move nrf_desktop to applications

### PR DESCRIPTION
**Pull request by pdunaj**
Jira:DESK-553

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
I am leaving the PR prefix as usual to make sure all nrf_desktop tests will trigger.
When @wiminordic is back we can fix this.

**Comment by pdunaj** [comment]
Hi @carlescufi , I have updated the codeowners file to follow the change of directories.

**Comment by pdunaj** [comment]
let's wait a bit - there should be one more test specific to nrf_desktop

**Comment by pdunaj** [comment]
It seems nrf_desktop CI executed and all tests are successful.

Hi @carlescufi , I think we can merge this one. I will check with @wiminordic tomorrow about any additional changes needed on CI side.

**Comment by carlescufi** [comment]
@pdunaj I am happy to merge this, but can you please double-check there are no additional changes required to the documentation? For example a list of samples somewhere?

**Comment by pdunaj** [comment]
Hi @carlescufi , I don't think so. I did grep nrf repo just in case.

**Pull request merged**
