### PR TITLE
applications: nrf_desktop: BLE bond use click_event

### PR DESCRIPTION
**Pull request by MarekPieta**
Change makes ble_bond module use click_event instead of button_event.

### CODE REVIEW

**Comment by MarekPieta** [comment]
@ppryga, coul you review ?

**Comment by MarekPieta** [comment]
Please, do not merge yet. I will add click detector configurations for keyboard and dongle.

**Comment by MarekPieta** [comment]
@pdunaj, everything is ready here. Can we merge ?

**Comment by pdunaj** [comment]
@MarekPieta , too many commits pushed to this PR - please tell when clarified.

**Comment by MarekPieta** [comment]
Sorry, I was working on this branch and accidentally pushed change from next PR. It's fixed now.

**Pull request merged**
