### PR TITLE
ext: cJSON: Update cJSON library to version v1.7.12

### PR DESCRIPTION
**Pull request by sigvartmh**
This commit updates the cJSON library to version v1.7.12.

Signed-off-by: Sigvart Hovland <sigvart.m@gmail.com>

### CODE REVIEW

**Comment by sigvartmh** [comment]
@joakimtoe Any reason why we shouldn't update the cJSON library?

**Comment by rlubos** [comment]
Is there any reason that cJSON needs to be updated, or is it just a bump to the most recent version?

Anyway, I was wondering whether we could use `west` for the cJSON instead of keeping the sources internally. The problem I see though is that its repo is quite bulky compared to the sources we need. And it brings it's own `CMakeLists.txt`, so it will likely cause conflicts.

**Comment by sigvartmh** [comment]
I want to(don't need) to create a PR which uses some of the new API introduced in a newer version but I do understand if you don't want to update it as it could break something.

**Comment by sigvartmh** [comment]
I do agree that west should be used to keep the source instead of having it internally. So that we handle cbor and cjson the same. However this is not the case, so any objection to getting this merged or will it have to wait?

**Comment by rlubos** [comment]
If you can confirm that `nrf_cloud`, which is the only user of this library, works correctly, I don't mind having this merged.

**Comment by jtguggedal** [comment]
@sigvartmh Could we rebase this one and see if it passes CI? The current cJSON is quite outdated, and I'm running into issues that can only be solved by bumping the version. I did some testing with the asset tracker, and both encoding and decoding seems to work fine. Also the `modem_info` lib that uses cJSON seems to work without modifications.

**Comment by sigvartmh** [comment]
Okei, I'll try to rebase and update. I'm a bit in favor of moving this whole thing into the manifest file but that would require some unit tests for **nrfcloud lib** and **modem_info** to ensure if one updates the manifest that it doesn't break it.

**Comment by sigvartmh** [comment]
I seem to have some FP issues with building asset tracker. Not sure if it's just the configuration on my machine or not. Should it be built with the zephyr toolchain?

**Comment by jtguggedal** [comment]
@sigvartmh It should buildb with the standard gnuarmemb for NCS, but will also work with the Zephyr toolchain for QEMU.
I hope to be able to test it before the end of the day, but tomorrow morning at latest. Btw, running the asset tracker and connecting to nRF Cloud tests both encoding and decoding using cJSON, so that's a fair sanity check.

**Comment by rlubos** [comment]
@jtguggedal Any success with testing?

**Comment by sigvartmh** [comment]
Compiled at least :dagger:

**Comment by jtguggedal** [comment]
Sorry about the delayed response. All worked as expected when I ran the asset tracker, testing both decoding and encoding in the local cloud codec, nrf_cloud codec and modem_info.

**Pull request merged**
