### PR TITLE
tests: bl_crypto: Adjust stack usage.

### PR DESCRIPTION
**Pull request by oyvindronningstad**
because it was assuming too high stack usage.
Change from 12384 to 4800.

Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

### CODE REVIEW

**Comment by sigvartmh** [comment]
What board do we build the test for. It is `ns` right?

**Comment by oyvindronningstad** [comment]
> What board do we build the test for. It is `ns` right?

It won't work with ns, since the app currently does not have access to B0's ABI.

**Comment by hakonfam** [comment]
Out of curiosity, why do we even need to set the stack size explicitly? Is the default not enough? If not, why is it necessary to lower it? Is it to get an indication on how much RAM the crypto library require?

**Comment by hakonfam** [comment]
FYI I was able to run the tests on 10090 with 4736 as the stack size

**Comment by oyvindronningstad** [comment]
> FYI I was able to run the tests on 10090 with 4736 as the stack size

Thanks, lowered it further, to 4800, to give a little leeway.

> Out of curiosity, why do we even need to set the stack size explicitly? Is the default not enough? If not, why is it necessary to lower it? Is it to get an indication on how much RAM the crypto library require?

The default is 1024. The test uses a lot of stack because the bootloader ABI for crypto needs a RAM buffer which is allocated on stack. The adjustment is to give a more realistic sense of the stack size needed since we've changed the RAM buffer size one or two times since the old stack size was set.

**Pull request merged**
