### PR TITLE
manifest: update fw-nrfconnect-zephyr

### PR DESCRIPTION
**Pull request by rlubos**
Update fw-nrfconnect-zephyr revision to reference latest upmerge

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
Still need to resolve `nrf_desktop` power management build issues.

**Comment by pdunaj** [comment]
@rlubos , I pushed a commit with required changes.

**Comment by rlubos** [comment]
@pdunaj Thank you, good to see that CI is green now :)

**Comment by pdunaj** [comment]
@rlubos np. Let's approve and merge ;)

**Comment by pdunaj** [comment]
Hi @Qbicz , can you have a quick look on on our part?

**Pull request merged**
