### PR TITLE
samples: nrf9160: gps: Add COEX0 configuration

### PR DESCRIPTION
**Pull request by bjda**
Adds support for a COEX0 configuration, to support the newer nRF9160 DK.
The MAGPIO method is preseved for compatibility with the older DK.

### CODE REVIEW

**Comment by bjda** [comment]
Should probably be included in 1.1 branch, as the GPS sample will not work on newer DKs without it.

**Comment by bjda** [comment]
cc @evenl @jtguggedal

**Comment by rlubos** [comment]
> `as the GPS sample will not work on newer DKs without it`

@bjda Do you mean the newer revisions of `PCA10090`? Does this change break compatibility with the older ones?

**Comment by bjda** [comment]
@rlubos Yes, and no, it does not break compatibility.

**Pull request merged**
