### PR TITLE
samples: nrf9160: Compile for boards defined in fw-nrfconnect-nrf

### PR DESCRIPTION
**Pull request by jhn-nordic**
…nnect-nrf

It is now also possible to compile nrf9160 samples for boards that are
defined in fw-nrfconnect-nrf repo. I.e the nrf9160_pca20035

Signed-off-by: Jon Helge Nistad <jon.helge.nistad@nordicsemi.no>

### CODE REVIEW

**Comment by hakonfam** [comment]
Not strictly related to this PR, but could affect it: why do we have a separate `nrf/cmake/boilerplate.cmake`? 

To me this looks like code that should be in `nrf/CMakeLists.txt`. I think it is a sane assumption that if you include the `fw-nrfconnect-nrf` module that this functionality is desired (even for samples not defined in the `fw-nrfconnect-nrf` repo).

**Comment by SebastianBoe** [comment]
We have a separate nrf/cmake/boilerplate.cmake for the code that needs to be run before zephyr/cmake/app/boilerplate.cmake.

For instance, https://github.com/NordicPlayground/fw-nrfconnect-nrf/blob/master/cmake/boilerplate.cmake#L29

**Comment by SebastianBoe** [comment]
Code that does not need to be run before zephyr/cmake/app/boilerplate.cmake should indeed be in nrf/CMakeLists.txt.

**Comment by lemrey** [comment]
Is `http_application_update` going to work on `nrf9160_pca20035`? Does it need specific partitions from the board DeviceTree?

**Comment by hakonfam** [comment]
@lemrey  I see no reason why it should not work.

**Pull request merged**
