### PR TITLE
Minor fixes in nus service

### PR DESCRIPTION
**Pull request by nordic-krch**
Fixing:
- missing include in nus.h
- missing log_strdup in log call

### CODE REVIEW

**Comment by nordic-krch** [comment]
fyi @KAGA164 @evenl

**Comment by lemrey** [comment]
Thanks @nordic-krch, since you're at it should we include another couple of headers?
One for `BT_UUID_DECLARE_128` and perhaps `zephyr/types`.

**Comment by nordic-krch** [comment]
@lemrey Done.

**Comment by nordic-krch** [comment]
@kapi-no could you take a look. It's rather trivial.

**Pull request merged**
