### PR TITLE
manifest: update fw-nrfconnect-zephyr

### PR DESCRIPTION
**Pull request by rlubos**
Update fw-nrfconnect-zephyr revision to reference latest upmerge.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
Hi @wiminordic , will our CI run for this PR?

**Comment by wiminordic** [comment]
> Hi @wiminordic , will our CI run for this PR?

Only smoke test.

**Comment by Qbicz** [comment]
@wiminordic the tests will not build unless we install Zephyr-SDK 0.10.0 on servers.

This PR is needed after upmerge: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/580

@rlubos, can you update to contain fix for https://github.com/zephyrproject-rtos/zephyr/issues/14786 ? (impact: people will not have to search google to download new Zephyr SDK)

**Comment by Qbicz** [comment]
Hi @carlescufi, @myrdyr is on vacation, could you update the Zephyr SDK to latest version in order to build the projects after upmerge?

**Comment by carlescufi** [comment]
> Hi @carlescufi, @myrdyr is on vacation, could you update the Zephyr SDK to latest version in order to build the projects after upmerge?
@Qbicz 
We are working with the Pylon team to get the Docker image updated since Thursday, but it's proving to be a bit challenging. We hope to have it done today.

**Comment by carlescufi** [comment]
@rlubos @Qbicz @pdunaj CI issues solved, but now there are some build errors

**Comment by Qbicz** [comment]
> @rlubos @Qbicz @pdunaj CI issues solved, but now there are some build errors

#580 should be included to fix build errors.

**Comment by rlubos** [comment]
@Qbicz Thanks, I'll integrate the fixes into this PR.

**Pull request merged**
