### PR TITLE
manifest: Update nrfxlib revision for new MPSL + BLE controller

### PR DESCRIPTION
**Pull request by rugeGerritsen**
See corresponding PR for more details: https://github.com/NordicPlayground/nrfxlib/pull/144

Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
FYI, @pdunaj , this PR includes some of the features you have requested

**Comment by pdunaj** [comment]
@rugeGerritsen this is much appreciated :)

**Comment by rugeGerritsen** [comment]
The Zephyr host does not properly handle the case when _Zephyr Read Static Addresses Command_ is not supported. It will the report a garbage value as its address. I will therefore add support for that command as well

**Comment by joerchan** [comment]
@grochu @pdunaj
Please let me know if you would like to do any additional testing other than CI for this PR.

**Comment by grochu** [comment]
> @grochu @pdunaj
> Please let me know if you would like to do any additional testing other than CI for this PR.

@joerchan thanks for asking. Would be good to test selected samples on nRF53 (S140 BLE Controller), since this device I think is not yet included in the CI. A candidate could be throughput, as it runs in different roles and also performs DLE.

**Pull request merged**
