### PR TITLE
applications: nrf_desktop: Switched logger mode

### PR DESCRIPTION
**Pull request by MarekPieta**
Switched logger mode to drop the oldest messages instead of new ones.

### CODE REVIEW

**Comment by MarekPieta** [comment]
@pdunaj, @Qbicz, could you review ?

**Comment by pdunaj** [comment]
Hi @nordic-krch , do you know if we can safely use logger from atomic context if we change to dropping the oldest message? I recall we dropped the new messages because there was some lock conflict or something but this was quite a long time ago so maybe it should be correct... or it was always correct.

**Comment by nordic-krch** [comment]
@pdunaj there is a `k_wakeup` being called from the logger context but it has been fixed (the issue with unlocking locked interrupts).

**Comment by pdunaj** [comment]
@nordic-krch , thanks. This should not be a problem.

**Comment by MarekPieta** [comment]
@pdunaj can we merge?

**Pull request merged**
