### PR TITLE
samples: aws_fota: Set proper configuration for download_client

### PR DESCRIPTION
**Pull request by rlubos**
download_client library added a static assert check on it's
configuration, which does not pass in the aws_fota sample.

As the sample and changes in the download_client were merged
in parallel, it was not reported by the CI in the original PR.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
@sigvartmh In this fix, I fall back to the default configuration which is proper for the `download_client` module and larger than the previous one (4k for the fragment and response). If you think it's too much, we can try to finetune, but this will require thorough testing.

**Comment by sigvartmh** [comment]
My initial assumption is that it would be totally fine if it falls back on the default as the fragment sizes shouldn't matter too much as long as the stack sizes of the threads are able to handle it.

Seems my assumption was correct and increasing the fragment size increased the speed of download to be about 50% faster.

**Comment by sigvartmh** [comment]
I would assume so since it works. I don't know what's the max fragment size the modem can handle. As far as I understand the modem is actually capable of streaming a HTTP response to  the application which means the fragment size would be limited by the available RAM in the application.

**Comment by rlubos** [comment]
If TLS is used, `download_client` will limit the fragment size to 2k by default.

**Comment by jtguggedal** [comment]
> If TLS is used, `download_client` will limit the fragment size to 2k by default.

@rlubos Good, thanks

**Comment by thst-nordic** [comment]
CI passed, Github is still displaying old result for some reason.   Good to go.

**Pull request merged**
