### PR TITLE
Asset tracker updates

### PR DESCRIPTION
**Pull request by jtguggedal**
A couple of updates to the asset tracker:

- Don't build with CONFIG_DEBUG=y by default. If this is enabled, the device will hang in error handler instead of rebooting when hitting a critical error (all errors are critical for the asset tracker at the moment)
- Increase system workqueue stack size as occasional overflow has been detected

### CODE REVIEW

**Comment by rlubos** [comment]
@joakimtoe @hmhalvorsen Any feedback?

**Comment by hmhalvorsen** [comment]
LGTM

**Comment by rlubos** [comment]
@jtguggedal I think you need a rebase in order to fix the CI - the old manifest points to `west` master instead of a fixed version, which seems to produce issues here.

**Comment by jtguggedal** [comment]
@rlubos Rebased, and CI seems to be happy.

**Comment by rlubos** [comment]
@jtguggedal Thank you, will merge once finished.

**Pull request merged**
