### PR TITLE
ci: Add nrf52840_pca20037 keyboard target to desktop CI artifacts.

### PR DESCRIPTION
**Pull request by wiminordic**
Replace deprecated pca10056 artifact with pca20037.

Signed-off-by: Wiktor Miesok <wiktor.miesok@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
I don't think pca10056 is deprecated (we will still keep I guess). Can't we have both?

**Comment by wiminordic** [comment]
> I don't think pca10056 is deprecated (we will still keep I guess). Can't we have both?

We could have both, the question is why? We don't run anything on PCA10056 HW. It is just the artifact that is not being copied, the building for this target is still done. Do you want to specifically keep this artifact exposed?

**Comment by pdunaj** [comment]
Hi @wiminordic , you are probably right. Since we don't use this for testing we can safely remove it. I think it will built anyway.

**Comment by wiminordic** [comment]
@carlescufi please merge.

**Pull request merged**
