### PR TITLE
samples: bluetooth: throughput: add nrf5340 configuration

### PR DESCRIPTION
**Pull request by kapi-no**
Added a configuration file for nRF5340 to the Bluetooth Throughput
sample.

Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>

### CODE REVIEW

**Comment by kapi-no** [comment]
Related to #1533 but can be merged independently

**Comment by joerchan** [comment]
@kapi-no Does this one work now, I suspect it might not select BT_PHY_UPDATE for the host image.
But maybe it is not required?

**Comment by kapi-no** [comment]
@joerchan, it seems to work using highest MTU (I haven't checked yet if PHY is correct). I see some error logs at the beginning on connection, but the throughput test can be run nonetheless. I am planning to investigate it further later on and check it more thoroughly.

PHY Update should be set by default (it was at least before).

Some changes that are required in the network sample are outlined in the readme
https://github.com/NordicPlayground/fw-nrfconnect-nrf/blob/master/samples/bluetooth/throughput/README.rst

**Comment by joerchan** [comment]
> PHY Update should be set by default (it was at least before).

@kapi-no Due to the bug being fixed here: #20760 it might be set off. Which is why I'm curious if this sample still works. CI is green though. Which is curious seeing as you said there was some error logs?

> it seems to work using highest MTU

MTU is a host concept, so it should work. The packets might still be fragmented on air (LL fragmentation and reassmebly). This fragmentation causes throughput to go down so we need DLE in the controller as well to acheive the highest possible throughput. And the same issue that is affecting PHY update also affects DLE.

**Comment by kapi-no** [comment]
@joerchan, have you looked at the Readme?

"If you use this board, you must add the following options to the network sample configuration:

CONFIG_BT_CTLR_TX_BUFFER_SIZE=251
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251"

**Comment by joerchan** [comment]
@kapi-no Please update with the error logs in the beginning of the connection

**Comment by kapi-no** [comment]
I investigated the issue with occasional error log which happened right upon connection for this sample:

```<err> bt_hci_driver: No available event buffers```

Even though this log seemed serious, the application did not crash and functioned properly. All HCI events that could not get their respectable event buffers from the pool turned out to be Advertising Reports. These types of events are discardable and I need to extend RPMsg HCI driver to handle it. It could be something similar to the code from the H4 HCI driver:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/bluetooth/hci/h4.c#L136

The BT_HCI_EVT_LE_ADVERTISING_REPORT event is tagged there as discardable and is discarded when its queue becomes full.

**Comment by kapi-no** [comment]
Manifest now points to the master branch of downstream zephyr.

**Pull request merged**
