### PR TITLE
subsys: net: Add support for keepalive_time_left() function.

### PR DESCRIPTION
**Pull request by jhn-nordic**
Added support for keepalive_time_left() function in the cloud
API and nrf_cloud backend.

Updated asset_tracker application to use the new functionality.

Signed-off-by: Jon Helge Nistad <jon.helge.nistad@nordicsemi.no>

### CODE REVIEW

**Comment by jhn-nordic** [comment]
Waiting for the upmerge including this PR to be merged https://github.com/zephyrproject-rtos/zephyr/pull/22004

**Comment by jtguggedal** [comment]
I think we should also use this new API in `mqtt_simple` to show best-practice of keep-alive handling in MQTT

**Comment by jhn-nordic** [comment]
> I think we should also use this new API in `mqtt_simple` to show best-practice of keep-alive handling in MQTT

Agree. Will update asset_tracker, cloud_client sample, nrf_cloud sample and mqtt simple.

**Comment by jhn-nordic** [comment]
aws_iot backend is now also updated.

**Comment by carlescufi** [comment]
Approved for merge once CI is green.

**Comment by carlescufi** [comment]
@jhn-nordic  please rebase against master

**Comment by carlescufi** [comment]
@jhn-nordic can you check the CI failure?

**Comment by jhn-nordic** [comment]
Was missing a ")". Hopefully it works now.

**Pull request merged**
