### PR TITLE
DNM: manifest: Update manifest for nrfxlib: pull/127/head

### PR DESCRIPTION
**Pull request by frkv**
-Adds missing changelog item for nrf_cc310_platform v0.9.1

Signed-off-by: Frank Audun Kvamtrø <frank.kvamtro@nordicsemi.no>

### CODE REVIEW

**Comment by frkv** [comment]
DNM because there is an addition of NFC nRF53 versions in nrfxlib that automatically gets added if this goes in

**Comment by tejlmand** [comment]
nrf has been updated to use nRF53 nfc lib.
https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1699

and
https://github.com/NordicPlayground/nrfxlib/pull/127 has been merged.

@frkv Please rebase and update manifest file.

**Comment by frkv** [comment]
> nrf has been updated to use nRF53 nfc lib.
> #1699
> 
> and
> [NordicPlayground/nrfxlib#127](https://github.com/NordicPlayground/nrfxlib/pull/127) has been merged.
> 
> @frkv Please rebase and update manifest file.

Excellent, will do!

**Comment by rlubos** [comment]
@frkv The `nrfxlib` commit in the manifest file is already ahead of the commit from this PR, any objections for closing the PR?

**Comment by frkv** [comment]
> @frkv The `nrfxlib` commit in the manifest file is already ahead of the commit from this PR, any objections for closing the PR?

That is what i was hoping for, all along

**Pull request closed without merging**
