### PR TITLE
samples: nrf9160: Increase heap size in various samples

### PR DESCRIPTION
**Pull request by rlubos**
Yet again the allocated heap size seems to be no longer enough for the samples to run. Increase it to 4k.

I'm getting slightly concerned about the increased heap requirements even for simple samples. I think it should be revisited, if the `at_cmd` driver, which's the reason for the increased heap consumption, does need to use the heap in a first place (why not a static memory?).

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by bjda** [comment]
Agreed. I get the feeling at_cmd was designed with the assumption that both AT commands and their respones would be quite small. This is the case for everything except security certificates, as far as I know.
Still, a simple synchronous AT command/response exchange shouldn't need dynamic allocation.

**Comment by lemrey** [comment]
This will solve the problem in the immediate future, and perhaps we should go ahead and merge it.
However, I agree that we should revisit the `at_cmd` and see if the heap usage can be removed.

**Comment by rlubos** [comment]
I've just discovered that with current heap implementation in Zephyr, requesting such a large buffer is simply a suicide. Unless we create a heap at least 4 times as big as requested buffer (~11k in our case), the **WHOLE** heap will be allocated only for that buffer, making the heap practically useless for others. So I don't see a point in using a heap here in the first place.

I'll close this PR and look into `at_cmd` instead.

**Comment by pizi-nordic** [comment]
> I've just discovered that with current heap implementation in Zephyr, requesting such a large buffer is simply a suicide. Unless we create a heap at least 4 times as big as requested buffer (~11k in our case), the WHOLE heap will be allocated only for that buffer, making the heap practically useless for others. So I don't see a point in using a heap here in the first place.

FYI: @carlescufi

**Comment by carlescufi** [comment]
> > I've just discovered that with current heap implementation in Zephyr, requesting such a large buffer is simply a suicide. Unless we create a heap at least 4 times as big as requested buffer (~11k in our case), the WHOLE heap will be allocated only for that buffer, making the heap practically useless for others. So I don't see a point in using a heap here in the first place.
> 
> FYI: @carlescufi

So, @rlubos could you please open an issue in upstream Zephyr covering this problem?

**Comment by rlubos** [comment]
@carlescufi I think the problem of inefficient heap implementation is a known issue upstream.

There already is a PR addressing the problem, proposing a new heap implementation, see https://github.com/zephyrproject-rtos/zephyr/pull/17628. I don't think there's a need to open an issue for problem that is already being covered.

**Pull request closed without merging**
