### PR TITLE
nrfxlib: bsdlib: bsdlib update version 0.7.2

### PR DESCRIPTION
**Pull request by tommi-m**
BSDLib update 0.7.2

This PR depends on: NordicPlayground/nrfxlib#165

Signed-off-by: Tommi Mammela <tommi.mammela@nordicsemi.no>

### CODE REVIEW

**Comment by tejlmand** [comment]
@evenl Does this PR deprecate this PR#2202 ?
If so, please close PR#2202

**Comment by tejlmand** [comment]
@tommi-m please add reference to corresponding nrfxlib PR, makes it easier to see the relation without going through the manifest file.

This PR depends on:
https://github.com/NordicPlayground/nrfxlib/pull/165

**Comment by eibe85** [comment]
I was a bit confused by this: This PR pulls in the changes form #167 into nrfxlib if you do a west update after checking this out but #167 depends on the changes in #2207 in order to compile. Should't the changes in #2207 and this be in the same PR?

**Comment by rlubos** [comment]
Since #2207 also updates `west.yml` file, I think we shoul close this PR to avoid confusion. One PR is enough.

**Comment by eibe85** [comment]
Yes, please, I got confused by this.

**Comment by rlubos** [comment]
Closing in favour of #2207.

**Pull request closed without merging**
