### PR TITLE
manifest: Update nrfxlib to include mpsl with API docs

### PR DESCRIPTION
**Pull request by rugeGerritsen**
Also updates mpsl and ble controller build revision.

Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>

See https://github.com/NordicPlayground/nrfxlib/pull/152

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
@MarekPieta , @grochu, do you want to do manual testing on this one, or will you rely on CI?

**Comment by grochu** [comment]
> @MarekPieta , @grochu, do you want to do manual testing on this one, or will you rely on CI?

We'll do a quick test in Protocols Team.

**Comment by pdunaj** [comment]
Hi @rugeGerritsen , @carlescufi , do you know why it is blocked and when it will be merged? Do you suspect there will be any more activity under this PR that will require re-testing?

**Comment by rugeGerritsen** [comment]
@pdunaj . We are waiting for a doc review

**Pull request merged**
