### PR TITLE
samples: nrf9160: Remove http_application_update

### PR DESCRIPTION
**Pull request by osaether**
The webserver `firmware.nrfcloud.com` is taken down permanently and
this sample should be removed. In addition , the functionality in this
sample is superseded by the `aws_fota` sample.

Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>

### CODE REVIEW

**Comment by sigvartmh** [comment]
In my opinion, we should keep the sample in and change the documentation to use an S3 bucket instead as we do for AWS FOTA. The reason for this is in-case a customer does not want to use AWS Jobs for their FOTA trigger, this sample showcases how you do FOTA through HTTP and is a much simpler and easier sample to use than AWS FOTA. This means modifying it is a lot easier, too, so they can quickly build their custom FOTA trigger from this sample.

**Comment by ru-fu** [comment]
> 
> 
> In my opinion, we should keep the sample in and change the documentation to use an S3 bucket instead as we do for AWS FOTA. The reason for this is in-case a customer does not want to use AWS Jobs for their FOTA trigger, this sample showcases how you do FOTA through HTTP and is a much simpler and easier sample to use than AWS FOTA. This means modifying it is a lot easier, too, so they can quickly build their custom FOTA trigger from this sample.

I agree that this is a good example to show a simple FOTA.
Not sure when we can update the documentation though, we're pretty swamped at the moment.

**Comment by sigvartmh** [comment]
@ru-fu I'll make changes to the documentation so if you have time you can take a quick look over it :)

**Comment by sigvartmh** [comment]
@ru-fu opened a new PR with doc updates https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1412

**Comment by thst-nordic** [comment]
CI FAILURE: /jenkins_workspace/workspace/connect-nrf_documentation_master/_build/nrf/rst/doc/nrf/doc/release-notes-0.4.0.rst:89: WARNING: undefined label: http_application_update_sample (if the link has no caption the label must precede a section header)

I think we need to add these warnings to the ignore list.

**Comment by rlubos** [comment]
The documentation was updated in https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1412 instead, closing.

**Pull request closed without merging**
