### PR TITLE
scripts: hid_configurator: Reboot after DFU

### PR DESCRIPTION
**Pull request by pdunaj**
Jira:DESK-663

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
Hi @wiminordic , do you know if this does the trick?

**Comment by wiminordic** [comment]
I used the artifacts from this PR, reboot is still not triggered.

**Comment by pdunaj** [comment]
@wiminordic thanks for checking I will look into it

**Comment by wiminordic** [comment]
@pdunaj sorry, wrong configurator used. I'll try with the fixed one.

**Comment by wiminordic** [comment]
Configurator files from this PR work fine, reboot is performed and DUT starts up with new FW.

**Pull request merged**
