### PR TITLE
bootloader: bl_crypto: Adapt to new nrf_oberon version

### PR DESCRIPTION
**Pull request by oyvindronningstad**
nrf_oberon has been updated from v2.0.7 to v3.0.0

### CODE REVIEW

**Comment by oyvindronningstad** [comment]
cc @sigvartmh @gbakke @frkv

**Comment by oyvindronningstad** [comment]
@gbakke I extracted this from the other PR (which has been merged). If you want to incorporate this with the changes you are making for bsdlib, feel free to cherry-pick :)

**Comment by ioannisg** [comment]
>/jenkins_workspace/workspace/fw-nrfconnect-nrf_PR-626/nrfxlib/bsdlib/lib/cortex-m33/hard-float/libbsd_nrf9160_xxaa.a(es256.c.o): In function `es256_key_generate':

es256.c:(.text.es256_key_generate+0x6e): undefined reference to `occ_ecdsa_p256_public_key'

**Comment by gbakke** [comment]
@ioannisg , this is expected as the library was swapped without backward compability. There is a PR for fixing this: https://github.com/NordicPlayground/nrfxlib/pull/40. Its a cyclic dependency here. This new lib also triggers a PR to go in first, before this build will get green (https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/561). @rlubos is on top of this. Rebase needed after these to PR's are in.

**Comment by rlubos** [comment]
`bsdlib` and `nrfxlib` manifest entry got updated, you can rebase now.

**Comment by oyvindronningstad** [comment]
> `bsdlib` and `nrfxlib` manifest entry got updated, you can rebase now.

Rebased

**Comment by sigvartmh** [comment]
Now that https://github.com/NordicPlayground/nrfxlib/pull/39 this should be merged @hakonfam

**Pull request merged**
