### PR TITLE
kconfig: add "Bootloader" menu

### PR DESCRIPTION
**Pull request by lemrey**
Add a "Bootloader" menu to avoid cluttering the top-level
Kconfig menu with bootloader-related entries.

### CODE REVIEW

**Comment by lemrey** [comment]
I would like to move `DFU_TARGET` and `FW_INFO` related entries somewhere else other than the top-level menu, probably under `Libraries`. @hakonfam  can you suggest a new place for `ARM_ENTRY_VENEERS_LIB_NAME` which appears quite odd in the top-level menu?

**Comment by hakonfam** [comment]
We could place the `ARM_ENTRY_VENEERS_LIB_NAME` under `SPM`, as it is only relevant for devices with trustzone enabled.

**Comment by ioannisg** [comment]
> We could place the `ARM_ENTRY_VENEERS_LIB_NAME` under `SPM`, as it is only relevant for devices with trustzone enabled.

Just wondering: Is it not needed at all when building the non-secure firmware?

**Comment by hakonfam** [comment]
> > We could place the `ARM_ENTRY_VENEERS_LIB_NAME` under `SPM`, as it is only relevant for devices with trustzone enabled.
> 
> Just wondering: Is it not needed at all when building the non-secure firmware?

It is the non-secure firmware that use it. But AFAIR the SPM kconfig is executed by the non-secure firmware as well. Its just the parts under the `if IS_SPM` that is not icnluded by the non-secure application.

**Comment by lemrey** [comment]
@oyvindronningstad can you please have a look too?

**Pull request merged**
