### PR TITLE
samples: bluetooth: Reduce central samples security level to 2

### PR DESCRIPTION
**Pull request by KAGA164**
This commit provides reduction of security level to level 2
without MITM protection.

Signed-off-by: Kamil Gawor <Kamil.Gawor@nordicsemi.no>

### CODE REVIEW

**Comment by KAGA164** [comment]
@kapi-no  @shantha-14 Please review

**Comment by thst-nordic** [comment]
We have enabled new documentation checks in the CI  
If you get a new failure in 'CI/Jenkins/DOC', try rebasing from master.  
If this doesn't fix things or you have other CI questions,  you can get help in the Teams chatroom 'NCS->NCS CI'

**Comment by joerchan** [comment]
@KAGA164 Looks ok. Any specific reason why we do this?
Should you match the change in central_hids with a similar change in peripheral_hids_keyboard and peripheral_hids_mouse perhaps?

**Comment by kapi-no** [comment]
CC: @qung

**Comment by qung** [comment]
CC: @elisabeth-solheim

**Comment by lemrey** [comment]
Shall we add this to the changelog @joerchan ?

**Comment by joerchan** [comment]
@lemrey No, don't have to add changes to samples to the changelog.

**Pull request merged**
