### PR TITLE
fwinfo: Rename ABI to EXT_API

### PR DESCRIPTION
**Pull request by oyvindronningstad**
Requested in PR #1378.

### CODE REVIEW

**Comment by hakonfam** [comment]
Please fix checkpatch issues. I agree with most (if not all) of the changes here. I understand why you want to throw it all in a single PR, and to me it sort of makes sense as it deals with the same code, and in the end it does not matter how many PRs were used getting the code in.

That being said, I'm not able to do a proper review of this because of its size, so please make sure that everything works as expected :D

**Comment by oyvindronningstad** [comment]
> Please fix checkpatch issues. I agree with most (if not all) of the changes here. I understand why you want to throw it all in a single PR, and to me it sort of makes sense as it deals with the same code, and in the end it does not matter how many PRs were used getting the code in.
> 
> That being said, I'm not able to do a proper review of this because of its size, so please make sure that everything works as expected :D

Yep it's a bit big :/.

This one is hard to split because everything is affected by the renaming. If you review by commits, you should find that there is one big commit (ONLY renaming) followed by 3 relatively small commits.  Hopefully it's manageable to look at the three small ones at least. Maybe even skim the renaming to see that nothing weird is going on.

**Comment by oyvindronningstad** [comment]
Build is green.

**Comment by oyvindronningstad** [comment]
This PR is now only renaming.

**Comment by hakonfam** [comment]
Can you update changelog?

**Comment by oyvindronningstad** [comment]
> Can you update changelog?

Done

**Comment by hakonfam** [comment]
I found this 

```
➜  nrf git:(pr-1685) rg "_ABI" 
subsys/fw_info/Kconfig
58:config FW_INFO_MAGIC_ABI_GETTER_INFO
➜  nrf git:(pr-1685) 
```

should it be updated?

**Comment by oyvindronningstad** [comment]
> FW_INFO_MAGIC_ABI_GETTER_INFO

It's removed by #1691

**Pull request merged**
