### PR TITLE
Add user interface output library

### PR DESCRIPTION
**Pull request by KAGA164**
This library added possibility to indicated event by leds or events. It allows for a significant simplification of samples and status signaling.

### CODE REVIEW

**Comment by carlescufi** [comment]
@KAGA164 can we please rename this somehow? UI implies drawing to a framebuffer, and this is completely different. Also, as @lemrey says, isn't there overlap between this and the existing button and LED library?

**Comment by KAGA164** [comment]
@carlescufi It seems to me that we do not have something like UI. Have you any proposal for a new name ? This library does not duplicate functions from dk_leds_and_buttons, it uses it and is another layer of abstraction.

**Comment by lemrey** [comment]
@KAGA164 My concern with arguing that this library is another level of abstraction is that it is yet _another_. With the introduction of this library we'd have three levels of abstraction, the driver plus two libraries, and we'll have 1/3 of the projects each use a different library. We should not aim to have this kind of fragmentation for a task as common and basic as blinking LEDs.

I would suggest to reconsider whether the (very) limited functionality of `dk_leds_and_buttons_library` couldn't be joined with the one of this library to handle common tasks like reading button/switch status and blinking LEDs in common patterns.

I thought "devkit" was a better name for the `dk_leds_and_buttons` library, perhaps this could give you some ideas.

**Comment by rakons** [comment]
The idea behind such a library is to make common decision how for example:
- High advertising
- Low advertising
- Whitelist advertising
- Connection fact
- Scanning
- ...
How this all would be presented to the user. Then, in every example we wish just to make:
- Show high advertising state
- Show connected

Instead of:
- Blink LED with 500 ms on and 500 ms off
- Light the LED on.

The approach here would:
- Simplify the example itself by moving the presentation layer outside of the example code.
- Makes it easier to manage and make sure that every example shows its state in similar way.
- When we would make a decision that something should be presented in other way - we can make it simple and consistent.
- When we wish to add a board that has 2 LEDs instead of 4 - we can move the whole conditional code to make a decision how to present all the states in different boards out of the sample code.

In second hand, in his own example, user may wish to use only dk_buttons_and_leds and would not like the overhead of the universal library for status presentation.

So as we may discuss the naming, I still think it is good idea to have such module as a separate library.

**Comment by jhn-nordic** [comment]
> In second hand, in his own example, user may wish to use only dk_buttons_and_leds and would not >like the overhead of the universal library for status presentation.
> 
> So as we may discuss the naming, I still think it is good idea to have such module as a separate library.

This was the hole idea with the dk_buttons_and_leds library. Hassle free interaction with buttons and leds on the DK. (Originally made because the slide switches on the nRF9160 DK bounces a lot).

**Comment by KAGA164** [comment]
This PR was replaced by: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/376
This one in now unusable because of switch from private to public of source fork.

**Pull request closed without merging**
