### PR TITLE
lib: Add user interface output library

### PR DESCRIPTION
**Pull request by KAGA164**
This is a continuation of the previous https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/244.
The old one was unusable because of switch from private to public of source fork.

### CODE REVIEW

**Comment by kapi-no** [comment]
@emdi, is this PR acceptable to you now (after discussion with @rakons, @KAGA164 and @jhn-nordic)?

**Comment by lemrey** [comment]
@kapi-no not really, I am still convinced it would be better to provide one library.

The functionality in `dk_buttons_and_leds` is so minimal that I don't see any benefit in keeping it as a _separate_ abstraction instead of merging its functionality with this other library. We should also consider that this is not a driver or a library that will be used in a product, but only in the context of samples/prototypes running on a DK. Basically, _we_ are going to be the users and I honestly doubt we need two libs for the task of blinking leds in the samples.

The moment there's two libraries, half of the samples will use one library and the other half will use the other; that's for sure, and that's something I would really like to avoid because it would defeat the whole purpose of having a _standardized_ way to show alerts/errors/activity across the samples. There will also be the question of _where_ new functionality should be implemented, in one library or the other.

I just can't convince myself that that's better than adding `toggle_led()`, `read_button()` to this library.

**Comment by kapi-no** [comment]
@carlescufi, we are unable to reach a consensus on this PR. The main discussion point is to decide if we should integrate the functionality of this library with ```dk_buttons_and_leds``` module (suggested by @lemrey) or keep it independent (as it is now). The discussion was started in the #244 PR and continues here. Could you nominate a code owner and let him decide how we should proceed?

**Comment by carlescufi** [comment]
I am more or less of the opinion of @lemrey here. Could we merge the dk_buttons_and_leds into this so that we have a single API to interface with? It seems a bit overkill to have both side-by-side to me, but I am open to discussion, @KAGA164 can you please provide arguments as to why we should keep them separate and independent?

There aren't really any code owners that deal with UI, so I think we need to discuss this among us. I will page people that I think might have something to say about this:

@pizi-nordic @pdunaj @joakimtoe @ioannisg @joerchan

**Comment by lemrey** [comment]
@carlescufi and others: more comments can be found on the old PR: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/244

**Comment by pizi-nordic** [comment]
I see that this code suffers on the same illness that affected BSP library from nRF5 SDK:
- It is DK-centric (It assumes that all the LEDs and Buttons are connected directly to the GPIO)
- It is BLE-centric (It allows you to monitor BLE state, but not other things).
- It is Example-centric (It cannot be easily used for other things that examples).

IMHO we should have something like this https://fabiobaltieri.com/2011/09/21/linux-led-subsystem/
- Generic LED and Button API (the same for polled and interrupt-based buttons).
- GPIO-LED, GPIO-Button driver (just API translation).
- Set of triggers (turn on LED when CPU is active, turn off when it is IDLE, turn on when BLE is conncted, turn off when it is disconnected).
- Ability to link triggers to the LED.

Ideally this should also support RGB leds and quadrature encoder (please check nRF5 Desktop requirements in the confluence).

**Comment by kapi-no** [comment]
I am not sure if everyone saw this comment from @rakons but this is a good summary of why we are planning to add this library:
> 
> 
> The idea behind such a library is to make common decision how for example:
> 
> - High advertising
> - Low advertising
> - Whitelist advertising
> - Connection fact
> - Scanning
> - ...
>
>   How this all would be presented to the user. Then, in every example we wish just to make:
> - Show high advertising state
> - Show connected
> 
> 
> Instead of:
> 
> - Blink LED with 500 ms on and 500 ms off
> - Light the LED on.
> 
> 
> The approach here would:
> 
> - Simplify the example itself by moving the presentation layer outside of the example code.
> - Makes it easier to manage and make sure that every example shows its state in similar way.
> - When we would make a decision that something should be presented in other way - we can make it simple and consistent.
> - When we wish to add a board that has 2 LEDs instead of 4 - we can move the whole conditional code to make a decision how to present all the states in different boards out of the sample code.
> 
> 
> In second hand, in his own example, user may wish to use only dk_buttons_and_leds and would not like the overhead of the universal library for status presentation.
> 
> So as we may discuss the naming, I still think it is good idea to have such module as a separate library.


So this library basically provides a presentation layer for various application states. For now, the state can be currently presented by:
- LEDs
- terminal logs

However, the user may add another output backend (e.g buzzer to beep periodically when the application is advertising).

@carlescufi
> can you please provide arguments as to why we should keep them separate and independent?

This library is another layer of abstraction. To make all the examples communicate with the user the same way (to limit maintenance). The user cannot change LEDs state directly (like in `dk_buttons_and_leds`) via `ui_out API` - they can use predefined states that are translated into the certain type of signalling (blinking with predefined period and so on). Additionally, this library is not only focused on LEDs. It can be configured to use logs to indicate certain application states (when there are no LEDs available on the board). Other forms of state signalling can also be introduced later on.

To sum it up, I imagine that `dk_buttons_and_leds` module should allow the user to directly control LEDs/buttons and the `ui_out` library should allow the user to display various application states in the preconfigured manner using different outputs (LEDs, logs, etc.)

@pizi-nordic 
> It is DK-centric (It assumes that all the LEDs and Buttons are connected directly to the GPIO)

Yes, it is a dependency from the dk_buttons_and_leds module.

> It is BLE-centric (It allows you to monitor BLE state, but not other things)

Yes, it's possible to indicate BLE states for now, but anyone can define states that are relevant for other application types if they decide to use this library in their samples. But maybe we should consider defining domain-specific states (e.g. BLE) in the separate files that can be included in compilation based on Kconfig configuration.

> It is Example-centric (It cannot be easily used for other things that examples).

Yes, the main purpose of this module to unify the way in which application states are presented in the samples. The samples are easier to maintain that way.

> IMHO we should have something like this https://fabiobaltieri.com/2011/09/21/linux-led-subsystem/

We can have a generic LED API, but this module is supposed to use it (not implement it).

**Comment by pizi-nordic** [comment]
> We can have a generic LED API, but this module is supposed to use it (not implement it).

So please implement it and then use ;-)

The key message from me is that we should make things which will be **reusable**. The layer you propose is reusable only in your group (who else in Nordic develops simple examples using BLE?).
With little more effort you can create something which will be more flexible and could save sombody else a lot of effort (both inside Nordic and outside).

**Comment by joerchan** [comment]
@KAGA164 This one has stalled. Do we need this, or can this PR be closed?

**Comment by KAGA164** [comment]
@joerchan This can be closed.

**Pull request closed without merging**
