### PR TITLE
Remove 'hide-defaults-note'

### PR DESCRIPTION
**Pull request by mbolivar**
Trivial

### CODE REVIEW

**Comment by mbolivar** [comment]
> Found the following issues, please fix and resubmit:
> 1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Remove 'hide-defaults-note'"

Since no subsystem applies, I'm going to ignore this unless it will block the merge.

**Comment by lemrey** [comment]
I think you'll need to prefix the commit message after all :)
You could use `kconfig` as aprefix.

**Comment by carlescufi** [comment]
@mbolivar please rebase and reformat the commit message line

**Comment by mbolivar** [comment]
@carlescufi @lemrey done!

**Comment by mbolivar** [comment]
> This doesn't fix a bug or improve documentation, so I'm blocking this until release.

Release is out, please merge.

**Comment by lemrey** [comment]
Release is out, dismissing @SebastianBoe to unblock the merge.

**Pull request merged**
