### PR TITLE
samples: nrf_desktop: Drop PCA63519

### PR DESCRIPTION
**Pull request by pdunaj**
PCA63519 is not being used anymore and it is not maintained. Decision was made to drop its support.

### CODE REVIEW

**Comment by pdunaj** [comment]
Hi @carlescufi , we are dropping support for PCA63519. I don't think anybody beside us is really using it and it was not maintained for some time. I think the best way would be to drop the board files too. Please tell if you have anything against that.

**Comment by Qbicz** [comment]
Can you rename second commit to "Remove obsolete PCA63519 code" ?

**Comment by pdunaj** [comment]
@Qbicz , sure. I will rebase the code at the same time

**Comment by carlescufi** [comment]
No objections but please add a line in the changelog

**Comment by pdunaj** [comment]
Hi @carlescufi , thanks. I was about to write to @ru-fu about that.

**Comment by pdunaj** [comment]
HI @ru-fu , we would need to add information about pca63519 not being supported.
The latest file is `doc/release-notes-0.3.0.rst` but I think this is for the previous release. Will you add this information while creating next release notes or should we do it?

**Comment by carlescufi** [comment]
@pdunaj no, it's up to you to add an entry here: https://github.com/NordicPlayground/fw-nrfconnect-nrf/wiki/Changelog (see the email I sent recently)

**Comment by lemrey** [comment]
@pdunaj I would have removed the board support and sample code in one commit.

**Pull request merged**
