### PR TITLE
samples: nrf9160: aws_fota: Wrong variable name for client_id

### PR DESCRIPTION
**Pull request by sigvartmh**
I missed an search and replace for a variable name when I did a refactoring this changes it so that it uses the `id_buf` which is supplied from the caller of the function. Also some fixups for compilation warnings.

### CODE REVIEW

**Comment by sigvartmh** [comment]
@hakonfam @oyvindronningstad feel free to review.

**Comment by sigvartmh** [comment]
Done

**Comment by lemrey** [comment]
Which compiler version where you using by the way? The one in Zephyr-SDK or?

**Comment by sigvartmh** [comment]
arm-none-eabi-gcc 7 q2 and 8 q4(8 q4 does not work anymore due to a bug in their trust zone implementation)

**Pull request merged**
