### PR TITLE
manifest: update zephyr and tinycbor

### PR DESCRIPTION
**Pull request by ioannisg**
Update zephyr and tinycbor as part of a regular upmerge.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
DNM until manifest contains SHA's

**Comment by ioannisg** [comment]
FYI @mbolivar here is the outcome of the comparison.
```

Comparing nrf/west.yml with zephyr/west.yml at revision upstream/master, sha: 7d7fed0d2bf1deee3a215591b2fd88edec17f99d

=== blacklisted zephyr projects in nrf:
none (OK)
=== non-blacklisted zephyr projects missing from nrf:
none (OK)
=== projects in both zephyr and nrf:
--- zephyr (zephyr):
diverged from upstream: 148 ahead, 530 behind
upstream revision: 7d7fed0d2bf1deee3a215591b2fd88edec17f99d
NCS revision: d6e67554cfeb28df5525e53c073f61a00836f283
downstream patches which are likely merged upstream (revert these if appropriate):
- 4ebad02e3e270169220a9959f8c9ea6ba88f2e28 ([nrf fromlist] cmake: Fix bug where DTS_BINDINGS_DIRS could only have one entry)
  Similar upstream commits:
  ba287d2b27190c87eb071f2a6fa5c29b87a4ff77 (cmake: Fix bug where DTS_BINDINGS_DIRS could only have one entry)
--- tinycbor (modules/lib/tinycbor):
diverged from upstream: 2 ahead, 1 behind
upstream revision: 6966f6140cb870b792330a5186020eb1f4151f3e
NCS revision: 543ecb7c8662580ef803d59ceda7bd3b8a84a11b
no downstream patches seem to have been merged upstream

Note: verbose output was omitted, use "west -v ncs-compare" for more details.

```

**Comment by ioannisg** [comment]
@thst-nordic  can you help investigating why the DOC build has failed?

**Comment by carlescufi** [comment]
@pdunaj can you take a look at the desktop failure?

**Comment by carlescufi** [comment]
@thst-nordic are you on top of the doc failure?

**Comment by thst-nordic** [comment]
I re-started this CI.  I'll take a look at the doc failure first thing tomorrow if still there.

**Comment by MarekPieta** [comment]
@carlescufi, I think that test failed because nrf_destkop firmware build fails without the DTS updates. It should work fine, when the commits will be added.

**Comment by ioannisg** [comment]
@pdunaj could you please provide some feedback here? We would like to close this upmerge round, as soon as CI passes; I would like to know if you have any objections to going forward with the upmerge.

**Comment by ioannisg** [comment]
I've up-merged tinycbor, so CI now re-runs with the right sha

**Pull request merged**
